'''
Consider you are a HR oprations manager in Vignan Software slotion , 
you will be receving applications from the candidate s for multiple roles 
you are having a list of job roles WRITE A PROGRM

1. TO VIEW THE CANDIDATES APPLICATIONS
2. BASED ON YOUR EVALUATION ON CV OF A CANDIDATE ,PRINT WEATHER HIS/HER CV IS SHORTLISTED OR NOT
    AND SHORTLISTED APPLICATIONS AND JOB ROLE
3. SCHEDULA AN INTERVIEW FOR THE PARTICULAR SHORTLISTED CANDIDATES
4. SEND A MESSAGE TO THE CANDIDATES TO UPDATE THE STATUS OF THEIR LEVEL 1 INTERVIEW FEEDBACK AND INFORM 
   WEATHER THEY ARE QUALIFIED OR NOT FOR FURTHER LEVEL INTERVIEW
5. SEND AN OFFERLETTER TO THE SHORTLISTED CANDIDATES.
'''
job_roles={'full stack developer','data engineer','java developer','data analyst'}


